name: docker

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        if: success()
        run: docker build -t morgul/rpgkeeper:latest -t morgul/rpgkeeper:${IMAGE_TAG} .

      - name: Push to docker registry (latest)
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push morgul/rpgkeeper:latest
          
      - name: Push to docker registry (${IMAGE_TAG})
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push morgul/rpgkeeper:${IMAGE_TAG}
