# ----------------------------------------------------------------------------------------------------------------------
# Build and Deploy docker images
#
# This action requires the following secrets to be set:
#   * RANCHER_ACCESS_KEY - API Access key created in Rancher.
#   * RANCHER_SECRET_KEY - API Secret key created in Rancher.
# ----------------------------------------------------------------------------------------------------------------------

name: Docker

on:
  push:
    branches:
      - master

  release:
    types: [published]

env:
  IMAGE_NAME: rpgkeeper

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set ENV Variables.
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Build docker
        if: success()
        run: docker build -t morgul/rpgkeeper:v${VERSION} .

      - name: Push docker
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push morgul/rpgkeeper:v${VERSION}

  # Deploys Beta docker
  deploy-beta:
    needs: push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set ENV Variables.
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Deploy Beta Site
        uses: yantadeu/rancher-deploy-action@v0.0.3
        env:
          RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
          RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
          RANCHER_URL_API: 'https://rancher.skewedaspect.com/v3'
          SERVICE_NAME: 'rpgkeeper-beta'
          DOCKER_IMAGE: 'morgul/rpgkeeper:v${VERSION}'
          DOCKER_IMAGE_LATEST: 'morgul/rpgkeeper:latest'

  # Deploys prod docker
  deploy-prod:
    needs: push
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v2

      - name: Set ENV Variables.
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Deploy Production Site
        uses: yantadeu/rancher-deploy-action@v0.0.3
        env:
          RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
          RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
          RANCHER_URL_API: 'https://rancher.skewedaspect.com/v3'
          SERVICE_NAME: 'rpgkeeper'
          DOCKER_IMAGE: 'morgul/rpgkeeper:v${VERSION}'
          DOCKER_IMAGE_LATEST: 'morgul/rpgkeeper:latest'
